### PR TITLE
More precise language on events

### PR DESCRIPTION
**Pull request by udidahan**
It is not required to make use of Entities within a microservice to raise events.

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[d501d23](https://github.com/udidahan/well-architected/commits/d501d234de41d91cb99a165e2465379c5a8f95d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[well-architected/mission-critical/mission-critical-application-design.md](https://github.com/udidahan/well-architected/blob/patch-2/well-architected/mission-critical/mission-critical-application-design.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/915b64c6-eecb-d366-4a84-4831c5e1bfda/202210110516298649-48/BuildReport?accessString=37c50e69c948b8b71b8f8968f7e6e4c3a20b0103c04e260980ef3e8fe59b7427).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/915b64c6-eecb-d366-4a84-4831c5e1bfda?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@calcof

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by heoelri** [comment]
Thanks for your contribution @udidahan.

#sign-off

**Comment by sebader** [comment]
Ok for me. @CalCof  please sign-off

**Comment by CalCof** [comment]
#sign-off

**Pull request merged**
