### PR TITLE
Update azure-application-gateway.md

### PR DESCRIPTION
**Pull request by asukumar22**
Added necessary KV error resolution using advisor documentation for clarity

### CODE REVIEW

**Comment by Court72** [comment]
@greg-lindsay

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by American-Dipper** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.
	
#label:"aq-pr-triaged"
#label:"pending-content-team/business-approval"
Cc: @MicrosoftDocs/public-repo-pr-review-team

**Review by ckittel — CHANGES_REQUESTED** [review]
Please resolve the merge conflict.

**Comment by asukumar22** [comment]
> Please resolve the merge conflict.

Updated the broken link that caused the merge conflict.

**Review by asukumar22 — COMMENTED** [review]
Updated the broken link for the doc.

**Review by ckittel — APPROVED** [review]

**Review by ckittel — DISMISSED** [review]
Still have merge conflict.

**Review by Jak-MS — APPROVED** [review]

**Pull request merged**
