### PR TITLE
Reservation Scope

### PR DESCRIPTION
**Pull request by yikeura700**
It is not possible to select a single resource as a reservation scope. "Resource group" is a minimum scope.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@yikeura700 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ckittel** [comment]
@yikeura700 -- can you please re-resolve the merge conflict on this PR or close if not longer relevant due to the updates that have already happened on this file.  We'll close out in a week if the merge conflicts haven't been resolved.  Thanks.

**Comment by ShannonLeavitt** [comment]
Closing per @ckittel comment [above](https://github.com/MicrosoftDocs/well-architected/pull/5#issuecomment-1398572214).

**Pull request closed without merging**
