### PR TITLE
fix AKS landing zone broken link

### PR DESCRIPTION
**Pull request by aysabzevar**
The link was broken.
It's fixed now.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@aysabzevar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@MGoedtel 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by MGoedtel — APPROVED** [review]
@aysabzevar - Thanks for creating this PR to correct the broken link.  I've reviewed the change and approve for merge.

**Comment by MGoedtel** [comment]
#sign-off

**Pull request merged**
