### PR TITLE
Update azure-application-gateway.md

### PR DESCRIPTION
**Pull request by asukumar22**
Added the web link to documentation on app gateway infrastructure for subnet size details.

### CODE REVIEW

**Comment by Court72** [comment]
@greg-lindsay

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by ckittel — CHANGES_REQUESTED** [review]
This PR breaks the table structure.  Cannot accept it as is.

**Comment by ckittel** [comment]
@asukumar22 - Your merge conflict needs to be resolved before we can take this further.

**Comment by ckittel** [comment]
Hey there Aarthi, going to close this PR as abandoned.  If you'd like to reopen this, please see all of the above feedback that needs to be addressed.

#please-close

**Pull request closed without merging**
