### PR TITLE
added custom field per Shweta

### PR DESCRIPTION
**Pull request by ndelgado**
Added:
ms.custom: internal-intro

### CODE REVIEW

**Comment by PRMerger15** [comment]
@ndelgado : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JasonWHowell** [comment]
@ndelgado maybe there's a private repo to use instead.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Comment by ckittel** [comment]
@ndelgado - I'm closing this public PR, if you'd like to reopen and point for `well-architected-pr`, it can be continued there.  Thanks.

**Pull request closed without merging**
