### PR TITLE
Linking to additional library that implements resiliency patterns

### PR DESCRIPTION
**Pull request by udidahan**

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[b3af81f](https://github.com/udidahan/well-architected/commits/b3af81f01ea010a7ef80c51df600b1de0d5cc812)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[well-architected/mission-critical/mission-critical-application-design.md](https://github.com/udidahan/well-architected/blob/patch-2/well-architected/mission-critical/mission-critical-application-design.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/915b64c6-eecb-d366-4a84-4831c5e1bfda/202210181149111427-51/BuildReport?accessString=6ebea2054e4052d3db887d586670c81ee7e810d43bd8b80a455ca29b23f5c0b8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/915b64c6-eecb-d366-4a84-4831c5e1bfda?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@calcof

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by udidahan** [comment]
Hey folks, just wanted to make sure this wasn't being forgotten. Thanks :)

**Comment by udidahan** [comment]
Bump ;)

**Comment by udidahan** [comment]
Friendly reminder that this is still waiting...

**Comment by Jak-MS** [comment]
@CalCof - nudge. can you take a look?

**Comment by udidahan** [comment]
Is there anything else I can do to help this get across the finish line?

**Comment by Court72** [comment]
@PageWriter-MSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Review by ckittel — APPROVED** [review]
LGTM

**Comment by udidahan** [comment]
Wonderful! Thanks so much for helping get this across the finish line.

**Pull request merged**
